### ISSUE TITLE
Unable to locate any plugins

### ISSUE THREAD

**Issue by vietanh85** [OpenTSDB/opentsdb-rpc-kafka#5]
I'm facing this error when trying to restart the opentsdb with plugin
[main] PluginLoader: Unable to locate any plugins of the type: net.opentsdb.tsd.HttpSerializer

**Comment by vietanh85** [comment]
I tried to put these following lines to the opentsdb.conf:
```
tsd.rpc.plugins = net.opentsdb.tsd.KafkaRpcPlugin
KafkaRpcPlugin.kafka.zookeeper.connect = localhost:2181
KafkaRpcPlugin.groups = test
KafkaRpcPlugin.test.topics = test
KafkaRpcPlugin.test.consumerType = raw
KafkaRpcPlugin.test.Deserializer = net.opentsdb.data.deserializers.JSONDeserializer
KafkaRpcPlugin.test.rate = 1000
KafkaRpcPlugin.test.threads = 1
```
Then I faced another issue:
```
Exception in thread "main" java.lang.RuntimeException: Initialization failed
	at net.opentsdb.tools.TSDMain.main(TSDMain.java:237)
Caused by: java.lang.RuntimeException: Failed to initialize class net.opentsdb.tsd.KafkaRpcPlugin
	at net.opentsdb.tsd.RpcManager.createAndInitialize(RpcManager.java:429)
	at net.opentsdb.tsd.RpcManager.initializeRpcPlugins(RpcManager.java:402)
	at net.opentsdb.tsd.RpcManager.instance(RpcManager.java:142)
	at net.opentsdb.tools.TSDMain.main(TSDMain.java:202)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.opentsdb.tsd.RpcManager.createAndInitialize(RpcManager.java:421)
	... 3 more
Caused by: java.lang.NoClassDefFoundError: joptsimple/internal/Strings
	at net.opentsdb.tsd.KafkaRpcPluginGroup.<init>(KafkaRpcPluginGroup.java:140)
	at net.opentsdb.tsd.KafkaRpcPlugin.createConsumerGroups(KafkaRpcPlugin.java:187)
	at net.opentsdb.tsd.KafkaRpcPlugin.initialize(KafkaRpcPlugin.java:89)
	... 8 more
Caused by: java.lang.ClassNotFoundException: joptsimple.internal.Strings
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 11 more
2018-02-27 11:49:50,060 INFO  [TSDBShutdown] TSDB: Flushing compaction queue
2018-02-27 11:49:50,061 INFO  [TSDBShutdown] TSDB: Completed shutting down the TSDB
```

**Comment by DheerajDang** [comment]
- Clone the repo from this [location](https://github.com/jopt-simple/jopt-simple.git). 
- Create the jar file using `mvn clean package` command.
- Copy this file to your OpenTSDB plugin directory as defined in the opentsdb config via `tsd.core.plugin_path`

**Comment by javaenthugm** [comment]
@vietanh85 ,
There are two issues in your configuration.

`KafkaRpcPlugin.test.Deserializer` should be replaced by `KafkaRpcPlugin.test.deserializer` (small 'd')

Add the following jar `jopt-simple-4.6.jar` in your 'plugin' folder

**Comment by mancubus77** [comment]
Thanks gents!
I get jopt-simple from maven [repo](https://mvnrepository.com/artifact/net.sf.jopt-simple/jopt-simple/4.6), compilation from git hub requires pom.xml modification
